//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLSApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int MLS { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> PriceCat { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> AreaCat { get; set; }
        public Nullable<int> Bed { get; set; }
        public Nullable<int> Bath { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Description { get; set; }
        public int AgentID { get; set; }
        public byte[] Picture { get; set; }
        public string PictureFileName { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
